### ISSUE TITLE
Using Arrow Functions -- saves times :)

### ISSUE THREAD

**Issue by askflow1111** [anaclaudiar/jammming#2]
-  If we use arrow functions then we wouldn't need to bind the function in the constructor 👍 

From: 
https://github.com/anaclaudiar/jammming/blob/2a2ec0403c424a55c02210ae36ebf53c00f5e1a3/src/components/App/App.js#L16
https://github.com/anaclaudiar/jammming/blob/2a2ec0403c424a55c02210ae36ebf53c00f5e1a3/src/components/App/App.js#L23-L31
To:
```
 addTrack = (track) => { 
   if(this.state.playlistTracks.find(savedTrack => savedTrack.id === track.id)){ 
     return; 
   } else { 
     let newArray = this.state.playlistTracks; 
     newArray.push(track); 
     this.setState({playlistTracks: newArray}); 
   } 
 } 
```

**Comment by anaclaudiar** [comment]
Done!
