### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by askflow1111** [anaclaudiar/jammming#3]
[Exceeds expectations] Great work!

**Great**

- Code's Structure is good!
- Lifting State! 👍 
- Seems to have really good understanding of React + JS 👍 👍 👍 
- Including Package.json + .gitignore files
- Keeping the files separately (Modularity) 💯 -- This would be a really great ++ when your app gets bigger, keeping the files separately and same files together like app.js + app.css.
- No errors in developer tools! (There is one when we save the list while it is empty, but it is really little)

**Suggested Improvements**
- Arrow functions saves time, if you would like to use :) https://github.com/anaclaudiar/jammming/issues/2

**Overall, Perfect! -- You seem to have really great understanding of React + JavaScript + API 
(To be honest I am impressed!) 👍
_(So keep up the good work! -- **To become better than yesterday!**) -- The more you advance the better you become!_

**Comment by anaclaudiar** [comment]
Fixed this one too " There is one when we save the list while it is empty", there is a message now if the playlist is empty.
Thank you for your review!
